// @ts-check

const sidebars = {
  mdwSidebar: [
    '00-start',
    '01-jak-recenzowac',
    '02-mapa-materialow',
    {
      type: 'category',
      label: 'Artykuły do recenzji',
      collapsed: false,
      items: [
        'artykuly/index',
        {
          type: 'category',
          label: 'Międzynarodowe Dni Wina w Jaśle',
          items: [
            'artykuly/wydarzenie/index',
        'artykuly/wydarzenie/czym-naprawde-sa-miedzynarodowe-dni-wina-w-jasle',
        'artykuly/wydarzenie/miedzynarodowe-dni-wina-w-jasle-jako-przekroj-polskiego-winiarstwa-czego-mozna-sie-spodziewac',
        'artykuly/wydarzenie/od-winnicy-do-wydarzenia-skad-bierze-sie-to-doswiadczenie',
        'artykuly/wydarzenie/polskie-winnice-w-jednym-miejscu-co-wyroznia-miedzynarodowe-dni-wina-w-jasle-na-tle-innych-wydarzen',
          ],
        },
        {
          type: 'category',
          label: 'Uczestnik i degustacja',
          items: [
            'artykuly/uczestnik-i-degustacja/index',
        'artykuly/uczestnik-i-degustacja/czy-trzeba-znac-sie-na-winie-zeby-przyjsc-na-miedzynarodowych-dniach-wina-w-jasle',
        'artykuly/uczestnik-i-degustacja/jak-czytac-etykiety-win-i-co-naprawde-z-nich-wynika',
        'artykuly/uczestnik-i-degustacja/jak-odnalezc-sie-na-degustacji-jesli-robisz-to-pierwszy-raz',
        'artykuly/uczestnik-i-degustacja/jak-przygotowac-sie-do-wydarzenia-winiarskiego-zeby-wyniesc-z-niego-wiecej-niz-tylko-degustacje',
        'artykuly/uczestnik-i-degustacja/jak-rozmawiac-z-winiarzem-o-co-warto-zapytac-podczas-wydarzenia',
        'artykuly/uczestnik-i-degustacja/miedzynarodowe-dni-wina-w-jasle-oczami-uczestnika',
        'artykuly/uczestnik-i-degustacja/najczestsze-bledy-podczas-degustacji-i-dlaczego-nie-trzeba-sie-nimi-przejmowac',
        'artykuly/uczestnik-i-degustacja/nie-tylko-degustacja-o-spotkaniach-i-rozmowach-podczas-wydarzenia',
        'artykuly/uczestnik-i-degustacja/pierwszy-raz-na-miedzynarodowych-dniach-wina-w-jasle-co-warto-wiedziec-przed-przyjazdem',
          ],
        },
        {
          type: 'category',
          label: 'Polskie winiarstwo',
          items: [
            'artykuly/polskie-winiarstwo/index',
        'artykuly/polskie-winiarstwo/czy-klimat-w-polsce-sprzyja-produkcji-wina-wyzwania-i-mozliwosci',
        'artykuly/polskie-winiarstwo/czy-polska-ma-swoj-styl-wina-jak-rozpoznawalne-sa-polskie-wina',
        'artykuly/polskie-winiarstwo/czy-polskie-wino-jest-dobre-jak-zmienila-sie-jego-jakosc-na-przestrzeni-lat',
        'artykuly/polskie-winiarstwo/dlaczego-male-winnice-dzialaja-inaczej-niz-duze-marki',
        'artykuly/polskie-winiarstwo/jakie-odmiany-winorosli-uprawia-sie-w-polsce-przeglad-najwazniejszych-szczepow',
        'artykuly/polskie-winiarstwo/jak-klimat-podkarpacia-wplywa-na-wina-z-regionu',
        'artykuly/polskie-winiarstwo/jak-rozwija-sie-polskie-winiarstwo-w-ostatnich-latach-liczby-trendy-i-kierunki',
        'artykuly/polskie-winiarstwo/jak-wyglada-przyszlosc-polskiego-winiarstwa-prognozy-i-kierunki-rozwoju',
        'artykuly/polskie-winiarstwo/jak-wyglada-rynek-wina-w-polsce-produkcja-sprzedaz-i-trendy',
        'artykuly/polskie-winiarstwo/jak-zmieniaja-sie-gusta-polakow-jesli-chodzi-o-wino',
        'artykuly/polskie-winiarstwo/male-winnice-w-polsce-jak-dzialaja-i-czym-roznia-sie-od-duzych-producentow',
        'artykuly/polskie-winiarstwo/odmiany-winorosli-uprawiane-w-okolicach-jasla-co-warto-wiedziec-jako-uczestnik-wydarzenia',
        'artykuly/polskie-winiarstwo/polskie-wino-co-warto-wiedziec-na-poczatek',
        'artykuly/polskie-winiarstwo/rocznik-ma-znaczenie-jak-pogoda-wplywa-na-wina-z-regionu',
          ],
        },
        {
          type: 'category',
          label: 'Enoturystyka',
          items: [
            'artykuly/enoturystyka/index',
        'artykuly/enoturystyka/dlaczego-warto-przyjechac-do-jasla-zeby-poznac-polskie-winnice-bez-objezdzania-calego-kraju',
        'artykuly/enoturystyka/enoturystyka-w-polsce-gdzie-jestesmy-dzis-na-tle-europy',
        'artykuly/enoturystyka/enoturystyka-w-polsce-jak-zwiedzac-winnice-i-planowac-wyjazdy',
        'artykuly/enoturystyka/gdzie-w-polsce-produkuje-sie-wino-najwazniejsze-regiony-winiarskie',
        'artykuly/enoturystyka/od-dolnego-slaska-po-podkarpacie-jak-roznorodne-sa-wina-prezentowane-podczas-wydarzenia',
        'artykuly/enoturystyka/polskie-winnice-gdzie-pojechac-i-czego-sie-spodziewac',
        'artykuly/enoturystyka/weekend-w-winnicy-w-polsce-jak-wyglada-i-ile-kosztuje',
          ],
        },
        {
          type: 'category',
          label: 'Jasło, historia i środowisko',
          items: [
            'artykuly/jaslo-historia-srodowisko/index',
        'artykuly/jaslo-historia-srodowisko/co-zmienilo-jasielskie-stowarzyszenie-winiarzy-vinum-pro-cultura-w-regionie',
        'artykuly/jaslo-historia-srodowisko/czego-juz-nie-ma-jak-wygladaly-pierwsze-edycje-wydarzenia',
        'artykuly/jaslo-historia-srodowisko/dlaczego-winiarze-w-jasle-dzialaja-razem',
        'artykuly/jaslo-historia-srodowisko/dwadziescia-edycji-miedzynarodowych-dni-wina-w-jasle-jak-roslo-to-wydarzenie',
        'artykuly/jaslo-historia-srodowisko/jak-jasielskie-stowarzyszenie-winiarzy-vinum-pro-cultura-buduje-winiarskie-jaslo',
        'artykuly/jaslo-historia-srodowisko/jak-powstaje-wino-w-regionie-jasielskim-od-uprawy-do-butelki',
        'artykuly/jaslo-historia-srodowisko/jak-takie-wydarzenie-zmienia-miasto-na-przykladzie-jasla',
        'artykuly/jaslo-historia-srodowisko/jak-wyglada-jaslo-w-trakcie-miedzynarodowych-dni-wina',
        'artykuly/jaslo-historia-srodowisko/jak-zaczely-sie-miedzynarodowe-dni-wina-w-jasle-historia-opowiedziana-przez-ludzi-i-archiwa',
        'artykuly/jaslo-historia-srodowisko/kim-jest-polski-winiarz-od-pasji-do-profesjonalnej-produkcji',
        'artykuly/jaslo-historia-srodowisko/miedzynarodowe-dni-wina-w-jasle-kiedys-i-dzis-co-sie-zmienilo',
        'artykuly/jaslo-historia-srodowisko/winiarze-miedzynarodowych-dni-wina-w-jasle-kogo-tu-spotkasz',
        'artykuly/jaslo-historia-srodowisko/winiarze-z-calej-polski-na-miedzynarodowych-dniach-wina-w-jasle-przeglad-regionow-i-stylow',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Plan publikacji i SEO',
      items: [
        'plan/index',
        'plan/plan-publikacji-maj-czerwiec',
        'plan/zalozenia-seo-ai',
      ],
    },
    {
      type: 'category',
      label: 'FAQ do doprecyzowania',
      items: [
        'faq/index',
        'faq/bilety-i-wejscie',
        'faq/degustacje',
        'faq/wystawcy-i-winnice',
        'faq/dojazd-i-noclegi',
      ],
    },
    {
      type: 'category',
      label: 'Uwagi merytoryczne',
      items: [
        'uwagi-merytoryczne/index',
        'uwagi-merytoryczne/pytania-do-pani-katarzyny',
        'uwagi-merytoryczne/kwestie-do-sprawdzenia',
      ],
    },
  ],
};

module.exports = sidebars;